# This workflow ensures all code being pushed to your repo. is formatted
name: Auto-Format

# Controls when the action will run. 
on:
  push:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Check format
        id: check
        uses: jfversluis/dotnet-format@v2
        with:
          action: "check"
          fail-fast: false

      - name: Run format
        if: steps.check.outputs.has-changes == 'true'
        uses: jfversluis/dotnet-format@v2
        with:
          action: "fix"
          workspace: "MySolution.sln"

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Auto code format
            file_pattern: '*.cs'
